[[language]]
name = "swift"
indent = { tab-width = 2, unit = " " }
formatter = { command = "swiftformat", args = [ "--baseconfig", "~/.swiftformat" ] }

[[language]]
name = "typescript"
formatter = { command = "dprint", args = [ "fmt", "--stdin", "typescript" ] }
auto-format = true

[[language]]
name = "tsx"
formatter = { command = "dprint", args = [ "fmt", "--stdin", "tsx" ] }
auto-format = true

[[language]]
name = "nix"
formatter = { command = "nixpkgs-fmt" }

[[language]]
name = "ruby"
formatter = { command = "bundle", args = ["exec", "rubocop", "--stdin", "foo.rb", "-a", "--stderr", "--fail-level", "fatal"] }

[[language]]
name = "erb"
formatter = { command = "erb-format", args = [ "--stdin" ] }
